# Generated by Django 4.0.3 on 2022-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_client_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='client_table_code',
            field=models.SlugField(max_length=3, verbose_name='client table code'),
        ),
    ]
