# Generated by Django 4.0.3 on 2022-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_clienttable_client_table_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='client_table_compound_id',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='client table compound id'),
        ),
    ]
