# Generated by Django 4.0.1 on 2022-02-01 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=60, verbose_name='Descrição')),
                ('unit', models.CharField(max_length=10, verbose_name='Unidade')),
                ('barcode', models.CharField(max_length=13, verbose_name='Código de barras')),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('image', models.ImageField(default='images/items/defaultimage.jpeg', upload_to='images/items/')),
                ('technical_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Numero do pedido')),
                ('status', models.CharField(choices=[('0', 'Digitação'), ('1', 'Transferido'), ('2', 'Registrado'), ('3', 'Faturado'), ('5', 'Entregue'), ('9', 'Cancelado')], max_length=1)),
                ('invoice_number', models.CharField(max_length=9, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do faturamento')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor total')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='Empresa')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.establishment', verbose_name='Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço unitario')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.item')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=60, verbose_name='Descrição')),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='Empresa')),
                ('items', models.ManyToManyField(through='orders.PriceItem', to='orders.Item')),
            ],
        ),
        migrations.AddField(
            model_name='priceitem',
            name='pricetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='orders.pricetable', verbose_name='Tabela de preço'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('history_type', models.IntegerField(choices=[(0, 'Inclusão'), (1, 'Alteração'), (2, 'Exclusão'), (3, 'Impressão'), (4, 'Observação')])),
                ('history_description', models.TextField(blank=True, verbose_name='Descrição do historico')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que fez a movimentacao.')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço unitario')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.item', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pricetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.pricetable', verbose_name='Tabela de preço'),
        ),
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_table_code', models.CharField(max_length=3, verbose_name='Código da tabela de Item')),
                ('description', models.CharField(max_length=60, verbose_name='Descrição')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('contracting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='Empresa Contratante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=60, verbose_name='Descrição')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('item_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable', verbose_name='Tabela de itens')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.itemcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable', verbose_name='Tabela de itens'),
        ),
        migrations.AddConstraint(
            model_name='pricetable',
            constraint=models.UniqueConstraint(fields=('company', 'table_code'), name='PriceTable compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.UniqueConstraint(fields=('pricetable', 'item'), name='PriceItem compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='ordereditem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='OrderedItem unique_together'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_number', 'establishment'), name='order compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='itemtable',
            constraint=models.UniqueConstraint(fields=('contracting', 'item_table_code'), name='ItemTable compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('item_table', 'category_code'), name='ItemCategory compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('item_table', 'item_code'), name='Item compound primary key'),
        ),
    ]
