# Generated by Django 4.0 on 2022-01-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bar_code',
            new_name='barcode',
        ),
    ]
