# Generated by Django 4.0.1 on 2022-01-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_company_type'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table_code',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricetable',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='Empresa'),
        ),
    ]
