# Generated by Django 4.0.2 on 2022-02-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_status_alter_company_status_and_more'),
        ('orders', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Item category', 'verbose_name_plural': 'Item categories'},
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_table_compound_id',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='ItemTable compound id'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
