# Generated by Django 4.0 on 2022-01-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_bar_code_item_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='verbose_name',
            new_name='name',
        ),
    ]
