# Generated by Django 4.0.1 on 2022-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item_note_itemcategory_note_order_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='verbose_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='verbose_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
