# Generated by Django 4.0 on 2022-01-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_verbose_name_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='description',
            field=models.TextField(default='sem descrição', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item'),
        ),
    ]
