# Generated by Django 4.0.2 on 2022-02-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_agentestablishment_options_and_more'),
        ('orders', '0004_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'item category', 'verbose_name_plural': 'item categories'},
        ),
        migrations.AlterModelOptions(
            name='itemtable',
            options={'verbose_name': 'item table', 'verbose_name_plural': 'item tables'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'verbose_name': 'ordered Item', 'verbose_name_plural': 'ordered Items'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'order history', 'verbose_name_plural': 'order history'},
        ),
        migrations.AlterModelOptions(
            name='priceitem',
            options={'verbose_name': 'price item', 'verbose_name_plural': 'price items'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'price table', 'verbose_name_plural': 'price tables'},
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.itemcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/items/defaultimage.jpeg', upload_to='images/items/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.SlugField(max_length=15, verbose_name='item code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_compound_id',
            field=models.CharField(editable=False, max_length=23, unique=True, verbose_name='item compound id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable', verbose_name='item table'),
        ),
        migrations.AlterField(
            model_name='item',
            name='technical_description',
            field=models.TextField(blank=True, verbose_name='technical description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_code',
            field=models.SlugField(max_length=8, verbose_name='category code'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_compound_id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='item category compound id'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='item_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable', verbose_name='item table'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='contracting'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_table_code',
            field=models.SlugField(max_length=3, verbose_name='item table code'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_table_compound_id',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='item table compound id'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='billing date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='client user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.establishment', verbose_name='establishment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=9, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='order amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(verbose_name='order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.pricetable', verbose_name='price table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Typing'), (2, 'Transferred'), (3, 'Registered'), (4, 'Billed'), (5, 'Delivered'), (0, 'Canceled')]),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='history_description',
            field=models.TextField(blank=True, verbose_name='history description'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='history_type',
            field=models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration'), ('E', 'Exclusion'), ('P', 'Printed'), ('N', 'Note')], max_length=2, verbose_name='history type'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='price_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='orders.pricetable', verbose_name='price table'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='items',
            field=models.ManyToManyField(through='orders.PriceItem', to='orders.Item', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='price_table_compound_id',
            field=models.SlugField(max_length=15, verbose_name='price table compound id'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='table_code',
            field=models.SlugField(max_length=7, verbose_name='table_code'),
        ),
    ]
