# Generated by Django 4.0.2 on 2022-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_item_options_alter_itemcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
    ]
