# Generated by Django 4.0.2 on 2022-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='price_table_compound_id',
            field=models.SlugField(editable=False, max_length=15, unique=True, verbose_name='price table compound id'),
        ),
    ]
