# Generated by Django 4.0.2 on 2022-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_priceitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
