# Generated by Django 4.0.2 on 2022-02-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_status_alter_company_status_and_more'),
        ('orders', '0008_alter_priceitem_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.client', verbose_name='client'),
            preserve_default=False,
        ),
    ]
