# Generated by Django 4.0.2 on 2022-03-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_agent_note_order_items_orderhistory_agent_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='history_description',
            field=models.CharField(max_length=800, verbose_name='history description'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='history_type',
            field=models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration'), ('E', 'Exclusion'), ('N', 'Note')], max_length=2, verbose_name='history type'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_history', to='orders.order', verbose_name='order'),
        ),
    ]
