# Generated by Django 4.0.2 on 2022-03-02 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_alter_orderhistory_history_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='history_type',
            field=models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration'), ('N', 'Note')], max_length=2, verbose_name='history type'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
