# Generated by Django 4.0.3 on 2022-03-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderhistory_history_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_history', to='orders.order', verbose_name='order'),
        ),
    ]
