# Generated by Django 4.0.3 on 2022-05-09 17:58

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_compound_id', models.CharField(editable=False, max_length=23, unique=True, verbose_name='item compound id')),
                ('item_code', models.SlugField(max_length=15, verbose_name='item code')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('unit', models.CharField(max_length=10, verbose_name='unit')),
                ('barcode', models.CharField(blank=True, max_length=15, verbose_name='barcode')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, size=[115, 87], upload_to='images/items/', verbose_name='image')),
                ('technical_description', models.CharField(blank=True, max_length=800, verbose_name='technical description')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_compound_id', models.CharField(editable=False, max_length=16, unique=True, verbose_name='item category compound id')),
                ('category_code', models.SlugField(max_length=8, verbose_name='category code')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
            },
        ),
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_table_compound_id', models.CharField(editable=False, max_length=7, unique=True, verbose_name='item table compound id')),
                ('item_table_code', models.SlugField(max_length=3, verbose_name='item table code')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'item table',
                'verbose_name_plural': 'item tables',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='unit price')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'price item',
                'verbose_name_plural': 'price items',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_table_compound_id', models.SlugField(editable=False, max_length=15, unique=True, verbose_name='price table compound id')),
                ('table_code', models.SlugField(max_length=7, verbose_name='table_code')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'price table',
                'verbose_name_plural': 'price tables',
            },
        ),
    ]
