# Generated by Django 4.0.3 on 2022-03-29 20:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='jpeg', keep_meta=True, null=True, quality=0, size=[115, 76.24], upload_to='images/items/', verbose_name='image'),
        ),
    ]
