# Generated by Django 4.0.3 on 2022-04-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='order id')),
                ('order_number', models.IntegerField(editable=False, verbose_name='order number')),
                ('status', models.IntegerField(choices=[(1, 'Typing'), (2, 'Transferred'), (3, 'Registered'), (4, 'Invoiced'), (5, 'Delivered'), (0, 'Canceled')])),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('invoicing_date', models.DateTimeField(blank=True, null=True, verbose_name='invoicing date')),
                ('invoice_number', models.CharField(blank=True, max_length=9, verbose_name='invoice number')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='order amount')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
                ('agent_note', models.CharField(blank=True, max_length=800, verbose_name='agent note')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.client', verbose_name='client')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='client user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.company', verbose_name='company')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.establishment', verbose_name='establishment')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration'), ('N', 'Note')], max_length=2, verbose_name='history type')),
                ('history_description', models.CharField(max_length=800, verbose_name='history description')),
                ('agent_note', models.CharField(blank=True, max_length=800, verbose_name='agent note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_history', to='order.order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order history',
                'verbose_name_plural': 'order history',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='unit price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('sequence_number', models.IntegerField(verbose_name='sequence number')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item', verbose_name='item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='order.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'ordered Item',
                'verbose_name_plural': 'ordered Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='order.OrderedItem', to='item.item', verbose_name='items'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.pricetable', verbose_name='price table'),
        ),
        migrations.AddConstraint(
            model_name='ordereditem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='OrderedItem unique_together'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('client', 'order_number'), name='order compound primary key'),
        ),
    ]
