# Generated by Django 4.0.3 on 2022-03-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(editable=False, verbose_name='order number')),
                ('status', models.IntegerField(choices=[(1, 'Typing'), (2, 'Transferred'), (3, 'Registered'), (4, 'Invoiced'), (5, 'Delivered'), (0, 'Canceled')])),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('invoicing_date', models.DateTimeField(blank=True, null=True, verbose_name='invoicing date')),
                ('invoice_number', models.CharField(blank=True, max_length=9, verbose_name='invoice number')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='order amount')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
                ('agent_note', models.CharField(blank=True, max_length=800, verbose_name='agent note')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='unit price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'ordered Item',
                'verbose_name_plural': 'ordered Items',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration'), ('N', 'Note')], max_length=2, verbose_name='history type')),
                ('history_description', models.CharField(max_length=800, verbose_name='history description')),
                ('agent_note', models.CharField(blank=True, max_length=800, verbose_name='agent note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_history', to='order.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order history',
                'verbose_name_plural': 'order history',
            },
        ),
    ]
