# Generated by Django 4.0.3 on 2022-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order compound primary key',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('client', 'establishment', 'order_number'), name='order compound primary key'),
        ),
    ]
