# Generated by Django 4.0.3 on 2022-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_order compound primary key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='sequence_number',
            field=models.IntegerField(default=1, editable=False, verbose_name='sequence number'),
            preserve_default=False,
        ),
    ]
