# Generated by Django 4.0.3 on 2022-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordereditem_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='sequence_number',
            field=models.IntegerField(verbose_name='sequence number'),
        ),
    ]
