# Generated by Django 4.0.2 on 2022-02-15 18:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='User code')),
                ('username', models.SlugField(verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_compound_id', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Id do Cliente')),
                ('client_code', models.SlugField(max_length=9)),
                ('vendor_code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_compound_id', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Id da tabela de clientes')),
                ('client_table_code', models.SlugField(max_length=2, verbose_name='Código da tabela de cliente')),
                ('description', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_compound_id', models.CharField(editable=False, max_length=7, unique=True, verbose_name='Id da empresa')),
                ('company_code', models.SlugField(max_length=3, verbose_name='Codigo da empresa')),
                ('name', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=10, verbose_name='Raiz do CNPJ')),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('note', models.TextField(blank=True)),
                ('client_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clienttable')),
            ],
        ),
        migrations.CreateModel(
            name='Contracting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracting_code', models.SlugField(max_length=3, unique=True, verbose_name='Contracting Code')),
                ('name', models.CharField(max_length=60)),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('active_users_limit', models.IntegerField(default=3, verbose_name='Active users limit')),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_compound_id', models.CharField(editable=False, max_length=11, unique=True, verbose_name='Id do estabelecimento')),
                ('establishment_code', models.SlugField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18, verbose_name='CNPJ')),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (0, 'Desativado')])),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting'),
        ),
    ]
