# Generated by Django 4.0.3 on 2022-03-07 16:22

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='user code')),
                ('username', models.SlugField(verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'agent establishment',
                'verbose_name_plural': 'agent establishments',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_compound_id', models.CharField(editable=False, max_length=16, unique=True, verbose_name='client compound id')),
                ('client_code', models.SlugField(max_length=9, verbose_name='client code')),
                ('vendor_code', models.CharField(blank=True, max_length=9, verbose_name='vendor code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('cnpj', models.CharField(max_length=10, verbose_name='CNPJ')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'client establishment',
                'verbose_name_plural': 'client establishments',
            },
        ),
        migrations.CreateModel(
            name='ClientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_compound_id', models.CharField(editable=False, max_length=6, unique=True, verbose_name='client table compound id')),
                ('client_table_code', models.SlugField(max_length=2, verbose_name='client table code')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'client table',
                'verbose_name_plural': 'client tables',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_compound_id', models.CharField(editable=False, max_length=7, unique=True, verbose_name='company compound id')),
                ('company_code', models.SlugField(max_length=3, verbose_name='company code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('cnpj_root', models.CharField(max_length=10, verbose_name='CNPJ root')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
                ('client_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clienttable', verbose_name='client table')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contracting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracting_code', models.SlugField(max_length=3, unique=True, verbose_name='contracting code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('active_users_limit', models.IntegerField(default=5, verbose_name='active users limit')),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
            ],
            options={
                'verbose_name': 'contracting',
                'verbose_name_plural': 'contractings',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='sesssion key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_compound_id', models.CharField(editable=False, max_length=11, unique=True, verbose_name='establishment compound id')),
                ('establishment_code', models.SlugField(max_length=3, verbose_name='establishment code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18, verbose_name='CNPJ')),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1)),
                ('note', models.CharField(blank=True, max_length=800, verbose_name='note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'establishment',
                'verbose_name_plural': 'establishments',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='contracting'),
        ),
    ]
