# Generated by Django 4.0 on 2022-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=9, unique=True, verbose_name='Código da empresa'),
        ),
    ]
