# Generated by Django 4.0.2 on 2022-02-15 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='item_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable'),
        ),
        migrations.AddField(
            model_name='clienttable',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting'),
        ),
        migrations.AddField(
            model_name='clientestablishment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_establishments', to='core.client'),
        ),
        migrations.AddField(
            model_name='clientestablishment',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establishment'),
        ),
        migrations.AddField(
            model_name='clientestablishment',
            name='price_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pricetable'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clienttable'),
        ),
        migrations.AddField(
            model_name='client',
            name='establishments',
            field=models.ManyToManyField(through='core.ClientEstablishment', to='core.Establishment'),
        ),
        migrations.AddField(
            model_name='agentestablishment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentestablishment',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.establishment'),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client', verbose_name='Client company'),
        ),
        migrations.AddField(
            model_name='user',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting'),
        ),
        migrations.AddField(
            model_name='user',
            name='establishments',
            field=models.ManyToManyField(through='core.AgentEstablishment', to='core.Establishment', verbose_name='Agent establishments'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(fields=('company', 'establishment_code'), name='Establishment compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('contracting', 'company_code'), name='Company compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='clienttable',
            constraint=models.UniqueConstraint(fields=('contracting', 'client_table_code'), name='ClientTable compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='clientestablishment',
            constraint=models.UniqueConstraint(fields=('client', 'establishment'), name='ClientEstablishment compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('client_table', 'client_code'), name='Client compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='agentestablishment',
            constraint=models.UniqueConstraint(fields=('agent', 'establishment'), name='AgentEstablishment compound primary key'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'contracting'), name='Username compound primary key'),
        ),
    ]
