# Generated by Django 4.0.1 on 2022-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('C', 'Contratante'), ('D', 'Distribuidora'), ('L', 'Lojista'), ('O', 'Outros')], max_length=1),
        ),
    ]
