# Generated by Django 4.0 on 2022-01-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pricetable_description_alter_priceitem_item'),
        ('core', '0002_alter_company_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.pricetable', verbose_name='Tabela preço'),
        ),
    ]
