# Generated by Django 4.0.1 on 2022-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracting',
            name='contracting_code',
            field=models.SlugField(max_length=3, unique=True, verbose_name='Contracting Code'),
        ),
    ]
