# Generated by Django 4.0.2 on 2022-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desativado'), (1, 'Ativado')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desativado'), (1, 'Ativado')]),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desativado'), (1, 'Ativado')]),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desativado'), (1, 'Ativado')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desativado'), (1, 'Ativado')]),
        ),
    ]
