# Generated by Django 4.0.2 on 2022-02-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_item_status'),
        ('core', '0003_alter_client_status_alter_company_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentestablishment',
            options={'verbose_name': 'agent establishment', 'verbose_name_plural': 'agent establishments'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='clientestablishment',
            options={'verbose_name': 'client establishment', 'verbose_name_plural': 'client establishments'},
        ),
        migrations.AlterModelOptions(
            name='clienttable',
            options={'verbose_name': 'client table', 'verbose_name_plural': 'client tables'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contracting',
            options={'verbose_name': 'contracting', 'verbose_name_plural': 'contractings'},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'establishment', 'verbose_name_plural': 'establishments'},
        ),
        migrations.AlterField(
            model_name='agentestablishment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_establishments', to=settings.AUTH_USER_MODEL, verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='agentestablishment',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.establishment', verbose_name='establishment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.SlugField(max_length=9, verbose_name='client code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_compound_id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='client compound id'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clienttable', verbose_name='client table'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.CharField(max_length=10, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='establishments',
            field=models.ManyToManyField(through='core.ClientEstablishment', to='core.Establishment', verbose_name='establishments'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='vendor code'),
        ),
        migrations.AlterField(
            model_name='clientestablishment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_establishments', to='core.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientestablishment',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establishment', verbose_name='establishment'),
        ),
        migrations.AlterField(
            model_name='clientestablishment',
            name='price_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pricetable', verbose_name='price table'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='client_table_code',
            field=models.SlugField(max_length=2, verbose_name='client table code'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='client_table_compound_id',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='client table compound id'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='contracting'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='company',
            name='client_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clienttable', verbose_name='client table'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=10, verbose_name='CNPJ root'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.SlugField(max_length=3, verbose_name='company code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_compound_id',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='company compound id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='contracting'),
        ),
        migrations.AlterField(
            model_name='company',
            name='item_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.itemtable', verbose_name='item table'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='active_users_limit',
            field=models.IntegerField(default=3, verbose_name='active users limit'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='contracting_code',
            field=models.SlugField(max_length=3, unique=True, verbose_name='contracting code'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='establishment_code',
            field=models.SlugField(max_length=3, verbose_name='establishment code'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='establishment_compound_id',
            field=models.CharField(editable=False, max_length=11, unique=True, verbose_name='establishment compound id'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='loggedinuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='sesssion key'),
        ),
        migrations.AlterField(
            model_name='loggedinuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client', verbose_name='client company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contracting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracting', verbose_name='contracting'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='establishments',
            field=models.ManyToManyField(through='core.AgentEstablishment', to='core.Establishment', verbose_name='agent establishments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='user code'),
        ),
    ]
