# Generated by Django 4.0.1 on 2022-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
