# Generated by Django 4.0.2 on 2022-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agentestablishment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='active_users_limit',
            field=models.IntegerField(default=5, verbose_name='active users limit'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1),
        ),
    ]
