# Generated by Django 4.0.2 on 2022-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_status_alter_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='clienttable',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, max_length=800, verbose_name='note'),
        ),
    ]
