# Generated by Django 4.0.3 on 2022-03-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderhistory_order'),
        ('core', '0006_alter_client_note_alter_clienttable_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientestablishment',
            name='price_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pricetable', verbose_name='price table'),
        ),
    ]
